antify/codex:
  - source: .editorconfig
    dest: .editorconfig
  - source: eslint.config.js
    dest: eslint.config.js
  - source: .github/workflows/sync-codex-files.yml
    dest: .github/workflows/sync-codex-files.yml
