export enum BaseInputType {
  date = 'date',
  datetime = 'datetime',
  datetimeLocal = 'datetime-local',
  email = 'email',
  hidden = 'hidden',
  month = 'month',
  number = 'number',
  password = 'password',
  search = 'search',
  tel = 'tel',
  text = 'text',
  time = 'time',
  url = 'url',
  week = 'week',
  range = 'range',
}
