export interface Country {
  value: string;
  label: string;
  dialCode: string;
  numericCode: number;
  flag?: string;
  phoneLength?: number | number[];
  mask?: string;
  isDefault?: boolean;
  [key: string]: unknown;
}

export const COUNTRIES: Country[] = [
  {
    value: 'GB',
    label: 'United Kingdom',
    dialCode: '+44',
    numericCode: 44,
    flag: '🇬🇧',
    mask: '#### ######',
  },
  {
    value: 'DE',
    label: 'Deutschland',
    dialCode: '+49',
    numericCode: 49,
    flag: '🇩🇪',
    mask: '### #######',
  },
  {
    value: 'FR',
    label: 'France',
    dialCode: '+33',
    numericCode: 33,
    flag: '🇫🇷',
    mask: '# ## ## ## ##',
  },
  {
    value: 'ES',
    label: 'España',
    dialCode: '+34',
    numericCode: 34,
    flag: '🇪🇸',
    mask: '### ### ###',
  },
  {
    value: 'IT',
    label: 'Italia',
    dialCode: '+39',
    numericCode: 39,
    flag: '🇮🇹',
    mask: '### #######',
  },
  {
    value: 'PL',
    label: 'Polska',
    dialCode: '+48',
    numericCode: 48,
    flag: '🇵🇱',
    mask: '### ### ###',
  },
  {
    value: 'AT',
    label: 'Österreich',
    dialCode: '+43',
    numericCode: 43,
    flag: '🇦🇹',
    mask: '### #######',
  },
  {
    value: 'BE',
    label: 'België',
    dialCode: '+32',
    numericCode: 32,
    flag: '🇧🇪',
    mask: '### ## ## ##',
  },
  {
    value: 'CH',
    label: 'Schweiz',
    dialCode: '+41',
    numericCode: 41,
    flag: '🇨🇭',
    mask: '## ### ## ##',
  },
  {
    value: 'NL',
    label: 'Nederland',
    dialCode: '+31',
    numericCode: 31,
    flag: '🇳🇱',
    mask: '## ########',
  },
  {
    value: 'PT',
    label: 'Portugal',
    dialCode: '+351',
    numericCode: 351,
    flag: '🇵🇹',
    mask: '### ### ###',
  },
  {
    value: 'SE',
    label: 'Sverige',
    dialCode: '+46',
    numericCode: 46,
    flag: '🇸🇪',
    mask: '## ### ## ##',
  },
  {
    value: 'NO',
    label: 'Norge',
    dialCode: '+47',
    numericCode: 47,
    flag: '🇳🇴',
    mask: '### ## ###',
  },
  {
    value: 'DK',
    label: 'Danmark',
    dialCode: '+45',
    numericCode: 45,
    flag: '🇩🇰',
    mask: '## ## ## ##',
  },
  {
    value: 'FI',
    label: 'Suomi',
    dialCode: '+358',
    numericCode: 358,
    flag: '🇫🇮',
    mask: '## ### ## ##',
  },
  {
    value: 'CZ',
    label: 'Česko',
    dialCode: '+420',
    numericCode: 420,
    flag: '🇨🇿',
    mask: '### ### ###',
  },
  {
    value: 'HU',
    label: 'Magyarország',
    dialCode: '+36',
    numericCode: 36,
    flag: '🇭🇺',
    mask: '## ### ####',
  },
  {
    value: 'GR',
    label: 'Ελλάδα',
    dialCode: '+30',
    numericCode: 30,
    flag: '🇬🇷',
    mask: '### #######',
  },
  {
    value: 'IE',
    label: 'Éire',
    dialCode: '+353',
    numericCode: 353,
    flag: '🇮🇪',
    mask: '## #######',
  },
  {
    value: 'RO',
    label: 'România',
    dialCode: '+40',
    numericCode: 40,
    flag: '🇷🇴',
    mask: '### ### ###',
  },
  {
    value: 'LT',
    label: 'Lietuva',
    dialCode: '+370',
    numericCode: 370,
    flag: '🇱🇹',
    mask: '### ## ###',
  },
  {
    value: 'LV',
    label: 'Latvija',
    dialCode: '+371',
    numericCode: 371,
    flag: '🇱🇻',
    mask: '#### ####',
  },
  {
    value: 'EE',
    label: 'Eesti',
    dialCode: '+372',
    numericCode: 372,
    flag: '🇪🇪',
    mask: '#### ####',
  },
];
