export interface Country {
  value: string;
  label: string;
  dialCode: string;
  numericCode: number;
  flag?: string;
  phoneLength?: number | number[];
  mask?: string;
  isDefault?: boolean;
  [key: string]: unknown;
}

export const COUNTRY_LOCALES: Record<string, Record<string, string>> = {
  de: {
    GB: 'Vereinigtes Königreich',
    DE: 'Deutschland',
    FR: 'Frankreich',
    ES: 'Spanien',
    IT: 'Italien',
    PL: 'Polen',
    AT: 'Österreich',
    BE: 'Belgien',
    CH: 'Schweiz',
    NL: 'Niederlande',
    PT: 'Portugal',
    SE: 'Schweden',
    NO: 'Norwegen',
    DK: 'Dänemark',
    FI: 'Finnland',
    CZ: 'Tschechien',
    HU: 'Ungarn',
    GR: 'Griechenland',
    IE: 'Irland',
    RO: 'Rumänien',
    LT: 'Litauen',
    LV: 'Lettland',
    EE: 'Estland',
  },
};

export const COUNTRIES: Country[] = [
  {
    value: 'GB',
    label: 'United Kingdom',
    dialCode: '+44',
    numericCode: 44,
    flag: '🇬🇧',
    mask: '#### ######',
  },
  {
    value: 'DE',
    label: 'Germany',
    dialCode: '+49',
    numericCode: 49,
    flag: '🇩🇪',
    mask: '### #######',
  },
  {
    value: 'FR',
    label: 'France',
    dialCode: '+33',
    numericCode: 33,
    flag: '🇫🇷',
    mask: '# ## ## ## ##',
  },
  {
    value: 'ES',
    label: 'Spain',
    dialCode: '+34',
    numericCode: 34,
    flag: '🇪🇸',
    mask: '### ### ###',
  },
  {
    value: 'IT',
    label: 'Italy',
    dialCode: '+39',
    numericCode: 39,
    flag: '🇮🇹',
    mask: '### #######',
  },
  {
    value: 'PL',
    label: 'Poland',
    dialCode: '+48',
    numericCode: 48,
    flag: '🇵🇱',
    mask: '### ### ###',
  },
  {
    value: 'AT',
    label: 'Austria',
    dialCode: '+43',
    numericCode: 43,
    flag: '🇦🇹',
    mask: '### #######',
  },
  {
    value: 'BE',
    label: 'Belgium',
    dialCode: '+32',
    numericCode: 32,
    flag: '🇧🇪',
    mask: '### ## ## ##',
  },
  {
    value: 'CH',
    label: 'Switzerland',
    dialCode: '+41',
    numericCode: 41,
    flag: '🇨🇭',
    mask: '## ### ## ##',
  },
  {
    value: 'NL',
    label: 'Netherlands',
    dialCode: '+31',
    numericCode: 31,
    flag: '🇳🇱',
    mask: '## ########',
  },
  {
    value: 'PT',
    label: 'Portugal',
    dialCode: '+351',
    numericCode: 351,
    flag: '🇵🇹',
    mask: '### ### ###',
  },
  {
    value: 'SE',
    label: 'Sweden',
    dialCode: '+46',
    numericCode: 46,
    flag: '🇸🇪',
    mask: '## ### ## ##',
  },
  {
    value: 'NO',
    label: 'Norway',
    dialCode: '+47',
    numericCode: 47,
    flag: '🇳🇴',
    mask: '### ## ###',
  },
  {
    value: 'DK',
    label: 'Denmark',
    dialCode: '+45',
    numericCode: 45,
    flag: '🇩🇰',
    mask: '## ## ## ##',
  },
  {
    value: 'FI',
    label: 'Finland',
    dialCode: '+358',
    numericCode: 358,
    flag: '🇫🇮',
    mask: '## ### ## ##',
  },
  {
    value: 'CZ',
    label: 'Czech Republic',
    dialCode: '+420',
    numericCode: 420,
    flag: '🇨🇿',
    mask: '### ### ###',
  },
  {
    value: 'HU',
    label: 'Hungary',
    dialCode: '+36',
    numericCode: 36,
    flag: '🇭🇺',
    mask: '## ### ####',
  },
  {
    value: 'GR',
    label: 'Greece',
    dialCode: '+30',
    numericCode: 30,
    flag: '🇬🇷',
    mask: '### #######',
  },
  {
    value: 'IE',
    label: 'Ireland',
    dialCode: '+353',
    numericCode: 353,
    flag: '🇮🇪',
    mask: '## #######',
  },
  {
    value: 'RO',
    label: 'Romania',
    dialCode: '+40',
    numericCode: 40,
    flag: '🇷🇴',
    mask: '### ### ###',
  },
  {
    value: 'LT',
    label: 'Lithuania',
    dialCode: '+370',
    numericCode: 370,
    flag: '🇱🇹',
    mask: '### ## ###',
  },
  {
    value: 'LV',
    label: 'Latvia',
    dialCode: '+371',
    numericCode: 371,
    flag: '🇱🇻',
    mask: '#### ####',
  },
  {
    value: 'EE',
    label: 'Estonia',
    dialCode: '+372',
    numericCode: 372,
    flag: '🇪🇪',
    mask: '#### ####',
  },
];
