import type {
  Country,
} from '../types';

export const COUNTRIES: Country[] = [
  {
    value: 'GB',
    label: {
      de: 'Vereinigtes Königreich',
      en: 'United Kingdom',
    },
    dialCode: '+44',
    numericCode: 44,
    flag: '🇬🇧',
    mask: '#### ######',
  },
  {
    value: 'DE',
    label: {
      de: 'Deutschland',
      en: 'Germany',
    },
    dialCode: '+49',
    numericCode: 49,
    flag: '🇩🇪',
    mask: '### #######',
  },
  {
    value: 'FR',
    label: {
      de: 'Frankreich',
      en: 'France',
    },
    dialCode: '+33',
    numericCode: 33,
    flag: '🇫🇷',
    mask: '# ## ## ## ##',
  },
  {
    value: 'ES',
    label: {
      de: 'Spanien',
      en: 'Spain',
    },
    dialCode: '+34',
    numericCode: 34,
    flag: '🇪🇸',
    mask: '### ### ###',
  },
  {
    value: 'IT',
    label: {
      de: 'Italien',
      en: 'Italy',
    },
    dialCode: '+39',
    numericCode: 39,
    flag: '🇮🇹',
    mask: '### #######',
  },
  {
    value: 'PL',
    label: {
      de: 'Polen',
      en: 'Poland',
    },
    dialCode: '+48',
    numericCode: 48,
    flag: '🇵🇱',
    mask: '### ### ###',
  },
  {
    value: 'AT',
    label: {
      de: 'Österreich',
      en: 'Austria',
    },
    dialCode: '+43',
    numericCode: 43,
    flag: '🇦🇹',
    mask: '### #######',
  },
  {
    value: 'BE',
    label: {
      de: 'Belgien',
      en: 'Belgium',
    },
    dialCode: '+32',
    numericCode: 32,
    flag: '🇧🇪',
    mask: '### ## ## ##',
  },
  {
    value: 'CH',
    label: {
      de: 'Schweiz',
      en: 'Switzerland',
    },
    dialCode: '+41',
    numericCode: 41,
    flag: '🇨🇭',
    mask: '## ### ## ##',
  },
  {
    value: 'NL',
    label: {
      de: 'Niederlande',
      en: 'Netherlands',
    },
    dialCode: '+31',
    numericCode: 31,
    flag: '🇳🇱',
    mask: '## ########',
  },
  {
    value: 'PT',
    label: {
      de: 'Portugal',
      en: 'Portugal',
    },
    dialCode: '+351',
    numericCode: 351,
    flag: '🇵🇹',
    mask: '### ### ###',
  },
  {
    value: 'SE',
    label: {
      de: 'Schweden',
      en: 'Sweden',
    },
    dialCode: '+46',
    numericCode: 46,
    flag: '🇸🇪',
    mask: '## ### ## ##',
  },
  {
    value: 'NO',
    label: {
      de: 'Norwegen',
      en: 'Norway',
    },
    dialCode: '+47',
    numericCode: 47,
    flag: '🇳🇴',
    mask: '### ## ###',
  },
  {
    value: 'DK',
    label: {
      de: 'Dänemark',
      en: 'Denmark',
    },
    dialCode: '+45',
    numericCode: 45,
    flag: '🇩🇰',
    mask: '## ## ## ##',
  },
  {
    value: 'FI',
    label: {
      de: 'Finnland',
      en: 'Finland',
    },
    dialCode: '+358',
    numericCode: 358,
    flag: '🇫🇮',
    mask: '## ### ## ##',
  },
  {
    value: 'CZ',
    label: {
      de: 'Tschechien',
      en: 'Czech Republic',
    },
    dialCode: '+420',
    numericCode: 420,
    flag: '🇨🇿',
    mask: '### ### ###',
  },
  {
    value: 'HU',
    label: {
      de: 'Ungarn',
      en: 'Hungary',
    },
    dialCode: '+36',
    numericCode: 36,
    flag: '🇭🇺',
    mask: '## ### ####',
  },
  {
    value: 'GR',
    label: {
      de: 'Griechenland',
      en: 'Greece',
    },
    dialCode: '+30',
    numericCode: 30,
    flag: '🇬🇷',
    mask: '### #######',
  },
  {
    value: 'IE',
    label: {
      de: 'Irland',
      en: 'Ireland',
    },
    dialCode: '+353',
    numericCode: 353,
    flag: '🇮🇪',
    mask: '## #######',
  },
  {
    value: 'RO',
    label: {
      de: 'Rumänien',
      en: 'Romania',
    },
    dialCode: '+40',
    numericCode: 40,
    flag: '🇷🇴',
    mask: '### ### ###',
  },
  {
    value: 'LT',
    label: {
      de: 'Litauen',
      en: 'Lithuania',
    },
    dialCode: '+370',
    numericCode: 370,
    flag: '🇱🇹',
    mask: '### ## ###',
  },
  {
    value: 'LV',
    label: {
      de: 'Lettland',
      en: 'Latvia',
    },
    dialCode: '+371',
    numericCode: 371,
    flag: '🇱🇻',
    mask: '#### ####',
  },
  {
    value: 'EE',
    label: {
      de: 'Estland',
      en: 'Estonia',
    },
    dialCode: '+372',
    numericCode: 372,
    flag: '🇪🇪',
    mask: '#### ####',
  },
  {
    value: 'US',
    label: {
      de: 'Vereinigte Staaten',
      en: 'United States',
    },
    dialCode: '+1',
    numericCode: 1,
    flag: '🇺🇸',
    mask: '### ### ####',
    isDefault: true,
  },
  {
    value: 'CA',
    label: {
      de: 'Kanada',
      en: 'Canada',
    },
    dialCode: '+1',
    numericCode: 1,
    flag: '🇨🇦',
    mask: '### ### ####',
  },
  {
    value: 'RU',
    label: {
      de: 'Russland',
      en: 'Russia',
    },
    dialCode: '+7',
    numericCode: 7,
    flag: '🇷🇺',
    mask: '### ### ## ##',
  },
  {
    value: 'UA',
    label: {
      de: 'Ukraine',
      en: 'Ukraine',
    },
    dialCode: '+380',
    numericCode: 380,
    flag: '🇺🇦',
    mask: '## ### ## ##',
  },
  {
    value: 'KZ',
    label: {
      de: 'Kasachstan',
      en: 'Kazakhstan',
    },
    dialCode: '+7',
    numericCode: 7,
    flag: '🇰🇿',
    mask: '### ### ## ##',
  },
  {
    value: 'TR',
    label: {
      de: 'Türkei',
      en: 'Turkey',
    },
    dialCode: '+90',
    numericCode: 90,
    flag: '🇹🇷',
    mask: '### ### ## ##',
  },
  {
    value: 'CN',
    label: {
      de: 'China',
      en: 'China',
    },
    dialCode: '+86',
    numericCode: 86,
    flag: '🇨🇳',
    mask: '### #### ####',
  },
  {
    value: 'JP',
    label: {
      de: 'Japan',
      en: 'Japan',
    },
    dialCode: '+81',
    numericCode: 81,
    flag: '🇯🇵',
    mask: '## #### ####',
  },
  {
    value: 'KR',
    label: {
      de: 'Südkorea',
      en: 'South Korea',
    },
    dialCode: '+82',
    numericCode: 82,
    flag: '🇰🇷',
    mask: '## #### ####',
  },
  {
    value: 'IL',
    label: {
      de: 'Israel',
      en: 'Israel',
    },
    dialCode: '+972',
    numericCode: 972,
    flag: '🇮🇱',
    mask: '## ### ####',
  },
  {
    value: 'IN',
    label: {
      de: 'Indien',
      en: 'India',
    },
    dialCode: '+91',
    numericCode: 91,
    flag: '🇮🇳',
    mask: '##### #####',
  },
];
